Update build-apk.yml

diff --git a/.github/workflows/build-apk.yml b/.github/workflows/build-apk.yml
--- a/.github/workflows/build-apk.yml
+++ b/.github/workflows/build-apk.yml
@@ -9,7 +9,7 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
     
     steps:
     - name: Checkout code
@@ -34,11 +34,22 @@ jobs:
           zlib1g-dev \
           libncurses5-dev \
           libncursesw5-dev \
-          libtinfo5 \
           cmake \
           libffi-dev \
           libssl-dev \
-          python3-pip
+          python3-pip \
+          build-essential \
+          libltdl-dev \
+          libreadline-dev \
+          libsqlite3-dev \
+          wget \
+          curl \
+          llvm \
+          xz-utils \
+          tk-dev \
+          libxml2-dev \
+          libxmlsec1-dev \
+          liblzma-dev
     
     - name: Set JAVA_HOME
       run: |
@@ -49,7 +60,7 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install buildozer cython==0.29.33
-        pip install -r requirements.txt
+        pip install -r requirements.txt || echo "requirements.txt not found, skipping..."
     
     - name: Cache Buildozer global directory
       uses: actions/cache@v4
